### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by prakharpande04** [sonipn/Firstproj#1]
this is a new issue

**Comment by sonipn** [comment]
what is issue?

**Comment by ghost** [comment]
Abracadabra

**Comment by sonipn** [comment]
chalo coding kare

**Comment by sonipn** [comment]
ek ek calculator banao dono

**Comment by sonipn** [comment]
@ShendeManas @prakharpande04

**Comment by sonipn** [comment]
@ShendeManas acknowledge

**Comment by prakharpande04** [comment]
https://github.com/prakharpande04/SL_lab1/blob/main/calc.py

**Comment by prakharpande04** [comment]
calculator

**Comment by sonipn** [comment]
good work @prakharpande04
